version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3309'
    expose:
      - '3309'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./my-db:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/1.sql
