# Generated by Django 3.1.5 on 2021-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='crated_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
